CREATE TABLE IF NOT EXISTS Cliente (
 idCliente INT NOT NULL AUTO_INCREMENT,
 Nom_Cliente VARCHAR(45),
 Usuario_Cliente VARCHAR(12),
 Senha_Cliente VARCHAR(12),
 Email_Cliente VARCHAR(45),
 Cpf_Cliente VARCHAR(15),
 Cep_Cliente INT(10),
 DataNasc_Cliente DATE,
 Sexo_Cliente VARCHAR(9),
 Telefone_Cliente VARCHAR(15),
 Estado_Cliente VARCHAR(20),
 Cidade_Cliente VARCHAR(20),
 Ender_Cliente VARCHAR(45),
 Bairro_Cliente VARCHAR(45),
 Num_Cliente INT(5),
 PRIMARY KEY (idCliente));
